import React, { useState, useEffect } from 'react';
import Confetti from 'react-confetti';

const Level4_Review = ({ data, back }) => {
  // State to handle window size for confetti
  const [windowDimension, setWindowDimension] = useState({ 
    width: window.innerWidth, 
    height: window.innerHeight 
  });

  // Detect window resize so confetti covers the whole screen
  useEffect(() => {
    const detectSize = () => {
      setWindowDimension({ 
        width: window.innerWidth, 
        height: window.innerHeight 
      });
    };
    window.addEventListener('resize', detectSize);
    return () => window.removeEventListener('resize', detectSize);
  }, []);

  // Helper to get nice names
  const getStakeholderName = (id) => {
    const names = {
      teachers: 'Teachers',
      students: 'Students',
      hm: 'Headmaster',
      parents: 'Parents',
      district: 'District Officer',
      community: 'Community'
    };
    return names[id] || id;
  };

  return (
    <div className="animate-fade-in text-white relative">
      
      {/* 🎆 THE CONFETTI EXPLOSION 🎆 */}
      <Confetti 
        width={windowDimension.width} 
        height={windowDimension.height} 
        recycle={false} // Stops after a few seconds
        numberOfPieces={500}
      />

      {/* Header */}
      <div className="text-center mb-8 print:hidden">
        <h2 className="text-4xl font-bold text-blue-400 mb-2">Mission Complete!</h2>
        <p className="text-gray-400">Your Program Design Blueprint is ready.</p>
      </div>

      {/* The "Paper" Document Preview */}
      <div className="bg-white text-slate-900 p-8 rounded-lg shadow-2xl max-w-3xl mx-auto mb-8 relative overflow-hidden print:shadow-none print:w-full print:max-w-none">
        
        {/* Decorative Stamp */}
        <div className="absolute top-4 right-[-40px] rotate-45 bg-red-600 text-white text-xs font-bold px-10 py-1 shadow-lg opacity-80 print:opacity-100">
          DRAFT LFA
        </div>

        {/* Branding for the PDF */}
        <div className="hidden print:block mb-6 border-b pb-4">
          <h1 className="text-3xl font-bold text-blue-900">SUTRA Project Design</h1>
          <p className="text-sm text-gray-500">Generated by Shikshagraha Logic Engine</p>
        </div>

        {/* Section 1: The Core Problem */}
        <div className="mb-8 border-b-2 border-slate-200 pb-6">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">
            01. Core Challenge
          </h3>
          <p className="text-2xl font-serif font-medium leading-relaxed">
            "{data.problem || "No problem defined."}"
          </p>
        </div>

        {/* Section 2: The Logic Matrix */}
        <div>
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4">
            02. Intervention Logic
          </h3>
          
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b-2 border-slate-800">
                <th className="py-2 w-1/3 text-sm font-bold">System Actor</th>
                <th className="py-2 w-2/3 text-sm font-bold">Key Activity / Intervention</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200">
              {data.stakeholders.length > 0 ? (
                data.stakeholders.map((id) => (
                  <tr key={id}>
                    <td className="py-4 font-bold text-blue-800">
                      {getStakeholderName(id)}
                    </td>
                    <td className="py-4 text-slate-600">
                      {data.activities[id] || <span className="italic text-gray-400">No action specified</span>}
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="2" className="py-4 text-center text-gray-400 italic">
                    No team selected.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Action Buttons (Hidden when printing) */}
      <div className="flex justify-between items-center pt-4 border-t border-slate-700 print:hidden">
        <button 
          onClick={back} 
          className="text-slate-400 hover:text-white font-semibold underline"
        >
          Make Changes
        </button>

        <button 
          onClick={() => window.print()}
          className="bg-green-600 hover:bg-green-500 text-white px-8 py-3 rounded-full font-bold text-lg shadow-lg shadow-green-500/30 flex items-center gap-2 transition-transform hover:scale-105"
        >
          <span>🖨️</span> Download Blueprint
        </button>
      </div>

    </div>
  );
};

export default Level4_Review;